name: play

on: push

jobs:
  uname:
    runs-on: macos-latest
    steps:
      - run: uname -a

  date:
    runs-on: macos-latest
    steps:
      - run: date --help
      - run: TZ=UTC date --date='2020-02-03T04:05:06+0900' +'%FT%T%z'
