name: play

on: push

jobs:
  uname:
    runs-on: macos-latest
    steps:
      - run: uname -a

  date:
    runs-on: macos-latest
    steps:
      - run: man date | col -b
      - run: man gdate | col -b

