name: play

on: push

jobs:
  uname:
    runs-on: macos-latest
    steps:
      - run: uname -a

  date:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./date.sh

